name: Actions

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    eslint:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node 26
              uses: actions/setup-node@v4
              with:
                node-version: 26
            
            - name: Install dependencies
              run: npm ci

            - name: Run Eslint
              uses: sibiraj-s/action-eslint@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                extensions: js,ts,css,vue
                working-directory: src
                package-manager: npm
    sonarqube:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}